sonar.projectKey=nextalk-auth-service
sonar.projectName=NexTalk Auth Service
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.host.url=http://localhost:9000

# Source and test paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# JaCoCo coverage report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/dto/**,**/entity/**,**/exception/**,**/mapper/**
